### PR TITLE
add EverSQL

### PR DESCRIPTION
**Pull request by etai4542**

### CODE REVIEW

**Comment by shlomi-noach** [comment]
EverSQL is a fantastic project. However, it is not open source and therefore does not comply with the conditions for this `awesome` listing. Thank you for submitting!

**Comment by etai4542** [comment]
I see, thanks for the feedback!

**Comment by etai4542** [comment]
Hi Shlomi,
I understand, thanks for letting me know and feel free to use EverSQL
anytime with this free license code:
SQL8ZTA

‫בתאריך יום ג׳, 18 באוק׳ 2022 ב-9:03 מאת ‪Shlomi Noach‬‏ <‪
***@***.***‬‏>:‬

**Comment by shlomi-noach** [comment]
@etai4542 thank you -- making sure you intended to publish this free license code in public?

**Comment by etai4542** [comment]
Oh no, just for you!

**Comment by etai4542** [comment]
Just to clarify, this code is for a single use, do not publish it.
Have a great day!

‫בתאריך יום ה׳, 3 בנוב׳ 2022 ב-11:46 מאת ‪Itay Stein‬‏ ***@***.***
‬‏>:‬

> Oh no, just for you!
>

**Comment by shlomi-noach** [comment]
@etai4542 well you have just published it :laughing: not sure if you realize we're chatting over a public GitHub PR page, https://github.com/shlomi-noach/awesome-mysql/pull/107. You had better invalidate that code.

**Comment by shlomi-noach** [comment]
I deleted your comment where you published the code. I don't even have it myself anymore.

**Comment by etai4542** [comment]
Thanks, I was unaware of the email exchange being the same as the comments 😅
Let me know if you're interested in getting the code in a more private manner 😉

**Comment by shlomi-noach** [comment]
Just make sure to invalidate it. Others may have subscribed to this PR

**Comment by yakirgb** [comment]
@etai4542 I recommend you to replace the code. 
BTW, I subscribed to this repo and it's in my mail.

**Comment by kedarvj** [comment]
The code isn't working now :P so I guess corrective measures are in-place!

**Comment by etai4542** [comment]
Yup, that’s right. Thanks for all concerned parties!

**Comment by shlomi-noach** [comment]
haha looks like _somebody_ snatched it. It wasn't me :laughing:

**Pull request closed without merging**
