### PR TITLE
Added DumpSync in README.md

### PR DESCRIPTION
**Pull request by Kremilly**
This PR updates the README.md file to include DumpSync in backup section.

### CODE REVIEW

**Review by dveeden — COMMENTED** [review]
License: MIT

Not sure if this has reached the right maturity to be included.

**Comment by Kremilly** [comment]
> License: MIT
> 
> Not sure if this has reached the right maturity to be included.

Ok, all right... I understand.

**Review by shlomi-noach — COMMENTED** [review]
Agree with @dveeden -- looks cool but too soon to include in this listing, sorry.

**Comment by Kremilly** [comment]
> Agree with @dveeden -- looks cool but too soon to include in this listing, sorry.

All right, thanks!

**Pull request closed without merging**
