### PR TITLE
Add YesMark

### PR DESCRIPTION
**Pull request by samlambert**
You know it makes sense.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Grrrrrrrrr!

**Comment by samlambert** [comment]
> Grrrrrrrrr

:wink: :wine_glass:

**Comment by MarkLeith** [comment]
Needs to be in a new Benchmark section. Also should add sysbench to it as well whilst you are at it..

**Comment by samlambert** [comment]
> Needs to be in a new Benchmark section. Also should add sysbench to it as well whilst you are at it..

Done.

**Comment by samlambert** [comment]
Gonna close this and loop back with a proper benchmarking section. We want to make this repo as useful as possible to people so it is best to stick with more mature tools :wink:.

**Pull request closed without merging**
