### PR TITLE
Adding SQLYog Community

### PR DESCRIPTION
**Pull request by TehShrike**
Also removing "fast, easy-to-use" from SequelPro because it seems overly opinionated, and having to use SequelPro myself, my opinion differs :-P

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Hi!
Thank you -- a couple comments:
1. Please do one pull request per item
2. I agree that the SequelPro description is subjective -- I'll look into.
3. Your SQLYog link points to google code, whereas the project has moved to github: https://github.com/webyog/sqlyog-community
4. However on that page I can mostly see promotional to the commercial editions; what's in the community edition? I tried following the "SQLyog comes in 3 editions. Compare all our editions-Learn more" link -- bu the community edition is not even listed there.

So 3+4 also don't seem to be very friendly to the reader.

**Comment by shlomi-noach** [comment]
SequelPro description rewritten at this time.

**Comment by Marc-T** [comment]
Hi,

IMHO SQLYog Community is not a "real" free software. The commercial editions are surely good softwares but the community edition is crippled, full of annoying nags,  with basic functionality (query editor, database browser, data export..)... All the functionnalities are available in other "real" free software.

Just my opinion.

**Comment by knutov** [comment]
I disagree. SQLyog Community has all features any developer really need. 
I'm using it, well, more then 10 years, I think.
the only feature I miss in community edition is ssh tunnels, but - I have mac/linux with ssh and windows with putty, or even vpn, so it's not a problem.

Visual editor is something that you may need or may not need. There are a lot of another tools for that. phpMyAdmin also do not has visual editing tool, and analyzing data, etc.

**Pull request closed without merging**
