### PR TITLE
ADD ILLA Cloud to GUI

### PR DESCRIPTION
**Pull request by JerryMaoMao**

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Hello and thank you! Can you please clarify, I see the open source GitHub project page. But is the service itself open source? Could I run my own service using 100% of the code published on GitHub?

**Comment by JerryMaoMao** [comment]
Hi there! 
Yes! this project on GITHUB is 100% self-hosted and you can use everything for free if you self-host the product!

**Comment by shlomi-noach** [comment]
Thank you for clarifying! What I would request, though, is for the link to point to the GitHub repo rather than to the current online service 🙏🏻

**Comment by JerryMaoMao** [comment]
Here you go
https://github.com/illacloud/illa-builder
this is the repo address!

**Comment by shlomi-noach** [comment]
Hi, please push a change to the PR with the GitHub link. Only one link is possible.

**Comment by JerryMaoMao** [comment]
Done

**Review by shlomi-noach — APPROVED** [review]

**Pull request merged**
