### PR TITLE
 Added an e-book 

### PR DESCRIPTION
**Pull request by aubertc**
The e-book is an open-source, free, set of lecture notes that covers the basics of SQL using maria db / mysql. The source code of the examples and problems is always available to download.

### CODE REVIEW

**Comment by datacharmer** [comment]
An impressive e-book! With almost all the material being open source, it's a far cry from the traditional university syllabus. 
I think it would be a fair addition to awesome-mysql.
Perhaps the next edition could be improved by adding dbdeployer as a database installation method.

**Comment by aubertc** [comment]
Thanks for your kind words and recommendation: [dbdeployer](https://www.dbdeployer.com/) is indeed a fine tool, and I'll make sure to add references to it in the next update of the notes.

**Comment by shlomi-noach** [comment]
Thank you for this contribution! I'm happy to include it, but, can you please make this a one liner with a single link to the main project's page? (that is, avoid the multiple links to the various chapters)

**Comment by aubertc** [comment]
@shlomi-noach  Good point. This is done with https://github.com/shlomi-noach/awesome-mysql/pull/93

**Pull request closed without merging**
