### PR TITLE
Add Moon Modeler

### PR DESCRIPTION
**Pull request by datensen**

### CODE REVIEW

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
I do not see that this is an open source project? Please let me know if I'm mistaken. This repo only lists open source projects.

**Comment by datensen** [comment]
> I do not see that this is an open source project? Please let me know if I'm mistaken. This repo only lists open source projects.

You are right. It is not an open source project, but a freeware version is available. For details, please visit:
https://www.datensen.com/blog/docs/free-er-diagram-tool/

**Comment by shlomi-noach** [comment]
Thank you for clarifying. In that case it unfortunately cannot be curated here.

**Comment by datensen** [comment]
OK. Thanks for your time.

**Pull request closed without merging**
